import Folder from '$lib/img/folder.svelte';
import PlayRectangle from '$lib/img/play_rectangle.svelte';

export let files = [
    {type: "folder", icon: Folder, fileName:"Animais", size: "size", date:"dd/mm/aaaa", anotation:false, selected: false, 
        videos: [{label: "Pato", anotated: false}, 
            {label: "Ganso", anotated: true}, 
            {label: "Leão", anotated: false}, 
            {label: "Cão", anotated: false}, 
            {label: "Galinha", anotated: false}, 
            {label: "Burro", anotated: false}, 
            {label: "Vaca", anotated: true}, 
            {label: "Formiga", anotated: false}, 
            {label: "Girafa", anotated: false}, 
            {label: "Porco", anotated: true}]},
    {type: "folder", icon: Folder, fileName:"Plantas", size: "size", date:"dd/mm/aaaa", anotation:true, selected: false, 
        videos: [{label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}]},
    {type: "file", icon: PlayRectangle, fileName:"Aprender", size: "size", date:"dd/mm/aaaa", anotation:false, selected: false, 
        videos: [{label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}]},
    {type: "folder", icon: Folder, fileName:"Escola", size: "size", date:"dd/mm/aaaa", anotation:false, selected: false, 
        videos: [{label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}]},
    {type: "file", icon: PlayRectangle, fileName:"Matemática", size: "size", date:"dd/mm/aaaa", anotation:true, selected: false, 
        videos: [{label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}]},
    {type: "folder", icon: Folder, fileName:"Inglês", size: "size", date:"dd/mm/aaaa", anotation:true, selected: false, 
        videos: [{label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}]},
    {type: "file", icon: PlayRectangle, fileName:"Família", size: "size", date:"dd/mm/aaaa", anotation:false, selected: false, 
        videos: [{label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}, 
            {label: "Gesto x", anotated: false}]}
    ];

